# ============================================================
# Docker Development Environment Template
# All build/run/stop operations managed via docker compose
# ============================================================

# ---------- Load config ----------
-include docker/config/.env
export

# ---------- Defaults ----------
USER_NAME  ?= $(shell whoami)
USER_UID   ?= $(shell id -u)
USER_GID   ?= $(shell id -g)
IMAGE_NAME ?= dev
IMAGE_TAG  ?= latest
CONTAINER_NAME ?= dev

# ---------- Compose command ----------
DC := docker compose -f docker/docker-compose.yml
ifneq (,$(wildcard docker/config/.env))
  DC += --env-file docker/config/.env
endif

.DEFAULT_GOAL := help

# ============================================================
# Help
# ============================================================
.PHONY: help
help:
	@echo "Docker Development Environment"
	@echo ""
	@echo "  Quick Start (3 steps for first time):"
	@echo "    make init                Initialize config"
	@echo "    make use T=python-3.12   Select template"
	@echo "    make up                  Build and start"
	@echo ""
	@echo "  Daily Usage:"
	@echo "    make build       Build image"
	@echo "    make up          Start container (detached)"
	@echo "    make run         Start interactively (enter bash)"
	@echo "    make shell       Attach to running container"
	@echo "    make down        Stop and remove container"
	@echo "    make restart     Restart container"
	@echo "    make logs        View container logs"
	@echo "    make ps          Show container status"
	@echo "    make exec CMD='xx' Run command in container"
	@echo "    make rebuild     Rebuild without cache"
	@echo "    make clean       Clean containers and images"
	@echo ""
	@echo "  One-step:"
	@echo "    make setup T=ros2-humble  Select + build + start"
	@echo ""
	@echo "  Templates:"
	@echo "    make list        List available templates"
	@echo "    make use T=xx    Select template"
	@echo ""
	@echo "  Config:"
	@echo "    docker/config/.env         System config (user, image, workspace)"
	@echo "    docker/config/env.custom    Custom env vars (injected at runtime)"

# ============================================================
# Initialize
# ============================================================
.PHONY: init
init:
	@mkdir -p docker/config
	@printf '%s\n' \
		'# Docker dev environment config (generated by make init)' \
		'' \
		'# User (match host to avoid permission issues)' \
		'USER_NAME=$(shell whoami)' \
		'USER_UID=$(shell id -u)' \
		'USER_GID=$(shell id -g)' \
		'' \
		'# Image' \
		'IMAGE_NAME=dev' \
		'IMAGE_TAG=latest' \
		'CONTAINER_NAME=dev' \
		'' \
		'# Workspace' \
		'WORKSPACE_DIR=$(CURDIR)' \
		'CONTAINER_WORKSPACE=workspace' \
		> docker/config/.env
	@if [ ! -f docker/config/env.custom ]; then \
		printf '%s\n' \
			'# Custom environment variables for the container' \
			'# Add KEY=VALUE lines here; they are injected at runtime (no rebuild needed).' \
			'# Example:' \
			'# ROS_DOMAIN_ID=42' \
			'# MY_APP_DEBUG=true' \
			> docker/config/env.custom; \
		echo "✓ Created: docker/config/env.custom"; \
	fi
	@echo "✓ Config generated: docker/config/.env"
	@echo ""
	@cat docker/config/.env

# ============================================================
# Template selection
# ============================================================
TPLDIR := docker/templates

.PHONY: list
list:
	@echo "Available templates:"
	@echo ""
	@echo "  ROS:"
	@echo "    ros1-noetic      ROS1 Noetic (Ubuntu 20.04)"
	@echo "    ros2-humble      ROS2 Humble (Ubuntu 22.04)"
	@echo "    ros2-foxy        ROS2 Foxy   (Ubuntu 20.04)"
	@echo "    ros2-jazzy       ROS2 Jazzy  (Ubuntu 24.04)"
	@echo ""
	@echo "  Languages:"
	@echo "    python-3.11      Python 3.11"
	@echo "    python-3.12      Python 3.12"
	@echo "    nodejs-18        Node.js 18"
	@echo "    nodejs-20        Node.js 20"
	@echo "    java-11          Java 11"
	@echo "    java-17          Java 17"
	@echo "    go-22            Go 1.22"
	@echo ""
	@echo "  System:"
	@echo "    ubuntu           Ubuntu 22.04 general-purpose"
	@echo ""
	@echo "Usage: make use T=<template>"

.PHONY: use
use:
ifndef T
	@echo "Please specify a template: make use T=<template>"
	@echo ""
	@$(MAKE) --no-print-directory list
else
	@tpl="$(T)"; \
	case "$$tpl" in \
	  ros1-noetic)   df=ros1/Dockerfile;         dir=ros1;; \
	  ros2-humble)   df=ros2/Dockerfile.humble;   dir=ros2;; \
	  ros2-foxy)     df=ros2/Dockerfile.foxy;     dir=ros2;; \
	  ros2-jazzy)    df=ros2/Dockerfile.jazzy;    dir=ros2;; \
	  python-3.11)   df=python/Dockerfile.3.11;   dir=python;; \
	  python-3.12)   df=python/Dockerfile.3.12;   dir=python;; \
	  nodejs-18)     df=nodejs/Dockerfile.18;     dir=nodejs;; \
	  nodejs-20)     df=nodejs/Dockerfile.20;     dir=nodejs;; \
	  java-11)       df=java/Dockerfile.11;       dir=java;; \
	  java-17)       df=java/Dockerfile.17;       dir=java;; \
	  go-22)         df=go/Dockerfile.22;         dir=go;; \
	  ubuntu)        df=ubuntu/Dockerfile;        dir=ubuntu;; \
	  *) echo "Unknown template: $$tpl"; $(MAKE) --no-print-directory list; exit 1;; \
	esac; \
	src="$(TPLDIR)/$$df"; \
	if [ ! -f "$$src" ]; then echo "Template file not found: $$src"; exit 1; fi; \
	cp "$$src" docker/Dockerfile && echo "✓ Dockerfile       ← $$src"; \
	if [ -f "$(TPLDIR)/$$dir/bashrc" ]; then \
	  cp "$(TPLDIR)/$$dir/bashrc" docker/config/bashrc && echo "✓ bashrc            ← $(TPLDIR)/$$dir/bashrc"; \
	fi; \
	if [ -f "$(TPLDIR)/$$dir/requirements.txt" ]; then \
	  cp "$(TPLDIR)/$$dir/requirements.txt" docker/requirements.txt && echo "✓ requirements.txt  ← $(TPLDIR)/$$dir/requirements.txt"; \
	fi; \
	if [ -f "$(TPLDIR)/$$dir/package.json" ]; then \
	  cp "$(TPLDIR)/$$dir/package.json" package.json && echo "✓ package.json      ← $(TPLDIR)/$$dir/package.json"; \
	fi; \
	if [ -f "$(TPLDIR)/$$dir/pom.xml" ]; then \
	  cp "$(TPLDIR)/$$dir/pom.xml" pom.xml && echo "✓ pom.xml           ← $(TPLDIR)/$$dir/pom.xml"; \
	fi; \
	echo ""; echo "Next: make build && make up"
endif

# ============================================================
# Build
# ============================================================
.PHONY: build
build:
	$(DC) build

.PHONY: rebuild
rebuild:
	$(DC) build --no-cache

# ============================================================
# Run
# ============================================================
.PHONY: up
up:
	@xhost +local:docker 2>/dev/null || true
	$(DC) up -d
	@echo "✓ Container started — run 'make shell' to enter"

.PHONY: run
run:
	@xhost +local:docker 2>/dev/null || true
	$(DC) run --rm --name $(CONTAINER_NAME) dev

.PHONY: shell
shell: enter
.PHONY: enter
enter:
	@$(DC) exec dev bash

.PHONY: exec
exec:
	@$(DC) exec dev $(CMD)

.PHONY: down
down:
	$(DC) down

.PHONY: stop
stop:
	$(DC) stop

.PHONY: restart
restart:
	$(DC) restart

.PHONY: logs
logs:
	$(DC) logs -f

.PHONY: ps
ps:
	$(DC) ps

# ============================================================
# Clean
# ============================================================
.PHONY: clean
clean:
	$(DC) down --rmi all --volumes 2>/dev/null || true
	@echo "✓ Clean complete"

# ============================================================
# One-step setup
# ============================================================
.PHONY: setup
setup:
ifndef T
	@echo "Usage: make setup T=<template>"
	@echo ""
	@$(MAKE) --no-print-directory list
else
	@$(MAKE) --no-print-directory use T=$(T)
	@$(MAKE) --no-print-directory build
	@$(MAKE) --no-print-directory up
endif

# ============================================================
# Configuration
# ============================================================
.PHONY: config
config:
	@echo "Current config:"
	@cat docker/config/.env 2>/dev/null || echo "(Not initialized — run 'make init')"
	@echo ""
	@echo "Current Dockerfile:"
	@head -3 docker/Dockerfile 2>/dev/null || echo "(none)"